name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish EasyAbp.GiftCardManagement.Application.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.Application/EasyAbp.GiftCardManagement.Application.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      - name: publish EasyAbp.GiftCardManagement.Application.Contracts.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.Application.Contracts/EasyAbp.GiftCardManagement.Application.Contracts.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.GiftCardManagement.Domain.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.Domain/EasyAbp.GiftCardManagement.Domain.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.GiftCardManagement.Domain.Shared.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.Domain.Shared/EasyAbp.GiftCardManagement.Domain.Shared.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.GiftCardManagement.EntityFrameworkCore.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.EntityFrameworkCore/EasyAbp.GiftCardManagement.EntityFrameworkCore.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.GiftCardManagement.HttpApi.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.HttpApi/EasyAbp.GiftCardManagement.HttpApi.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.GiftCardManagement.HttpApi.Client.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.HttpApi.Client/EasyAbp.GiftCardManagement.HttpApi.Client.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.GiftCardManagement.MongoDB.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.MongoDB/EasyAbp.GiftCardManagement.MongoDB.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.GiftCardManagement.Web.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.GiftCardManagement.Web/EasyAbp.GiftCardManagement.Web.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}